// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmYzTF_GPFYLf1R8EAOpdddDOPEywZ8eo',
    appId: '1:115903151583:web:074032b7bf8fe9df86d86a',
    messagingSenderId: '115903151583',
    projectId: 'flutter--chat-df2fb',
    authDomain: 'flutter--chat-df2fb.firebaseapp.com',
    storageBucket: 'flutter--chat-df2fb.appspot.com',
    measurementId: 'G-5NFSGKX8BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc0nKiF95Osw4HHIeVWGU1nr4Dei908w0',
    appId: '1:115903151583:android:1eb84a2d59f539ec86d86a',
    messagingSenderId: '115903151583',
    projectId: 'flutter--chat-df2fb',
    storageBucket: 'flutter--chat-df2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyj5rdKPDRgADJ9GCR7veZEfm3LVEosaE',
    appId: '1:115903151583:ios:85929ba002daae3486d86a',
    messagingSenderId: '115903151583',
    projectId: 'flutter--chat-df2fb',
    storageBucket: 'flutter--chat-df2fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyj5rdKPDRgADJ9GCR7veZEfm3LVEosaE',
    appId: '1:115903151583:ios:85929ba002daae3486d86a',
    messagingSenderId: '115903151583',
    projectId: 'flutter--chat-df2fb',
    storageBucket: 'flutter--chat-df2fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmYzTF_GPFYLf1R8EAOpdddDOPEywZ8eo',
    appId: '1:115903151583:web:f69bf42531de9d6c86d86a',
    messagingSenderId: '115903151583',
    projectId: 'flutter--chat-df2fb',
    authDomain: 'flutter--chat-df2fb.firebaseapp.com',
    storageBucket: 'flutter--chat-df2fb.appspot.com',
    measurementId: 'G-VY837VMFEJ',
  );
}
